* Suggested plugins~
        Universal Text Linking~
        (http://www.vim.org/scripts/script.php?script_id=293) general support for
        text linking. The hyperlinks feature of vim-orgmode depends on this plugin.
* repeat~
        (http://www.vim.org/scripts/script.php?script_id=2136)
        Repeat actions that would not be repeatable otherwise. This plugin is
        needed when you want to repeat the previous orgmode action.
* taglist~
        ([http://www.vim.org/scripts/script.php?script_id=273)
        Display tags for the currently edited file. Vim-orgmode ships with support
        for displaying the heading structure and hyperlinks in the taglist plugin.
* tagbar~
        (http://www.vim.org/scripts/script.php?script_id=3465)
        A new approach to displaying tags for the currently edited file.
        Vim-orgmode ships with support for displaying the heading structure and
        hyperlinks in the tagbar plugin.
* speeddating~
        (http://www.vim.org/scripts/script.php?script_id=2120)
        In-/decrease dates the vim way: C-a and C-x. Dates and times in the
        orgmode format can be in-/decreased if this plugins is installed.
* Narrow Region~
        (http://www.vim.org/scripts/script.php?script_id=3075)
        Emulation of Emacs' Narrow Region feature. It might be useful when dealing
        with large orgmode files.
* pathogen~
        (http://www.vim.org/scripts/script.php?script_id=2332)
        Easy management of multiple vim plugins.
* calendar~
        (http://www.vim.org/scripts/script.php?script_id=52)
        This plugin will create a calendar window for timestamp insertion.
* SyntaxRange~
        (http://www.vim.org/scripts/script.php?script_id=4168)
        Use proper syntax highlighting for code blocks such as: >
#+BEGIN_SRC cpp
int i = 1;
#+END_SRC
<
